# Discussion and Conclusions

In this final chapter we discuss what was accomplished in this thesis, the limitations of this work, and potential areas for further research.

The Trinity of Covariation is a guiding metaphor for the mathematical notions developed in this work, with the core motivation that studying coordinated changes in structure is a way of aggregating information about systems. We sought to construct more precise mathematical notions that in some sense exemplify or instantiate this metaphor. The instantiations of this metaphor developed in this thesis include multilinear correlations, Nightingale's correlation, inner correlations, Agnesian operators, and grade entropies.

Multilinear correlations, Nightingales's correlation, and inner correlation were all attempts to generalize correlation from its usage in introductory statistics by accommodating multiple variables. Nightingale's correlation focused on a generalization of norms, and inner correlation was based on a generalization of inner products. These functions are all statistics, and because statistics are functions of random variables it is also the case that statistics are themselves random variables. Any random variable has a distribution function, even if it is degenerate. In most practical cases we suspect that the distribution will not be degenerate. There is not an easy way to derive what the distribution of a statistic should be, even when a joint probability model for the input variables is given. While the distribution of summations of random variables can be approached with convolutions or Fourier transforms, the distribution of products of random variables are less easily obtained. Existing methods often require an assumption of measure independence, which is precisely one of properties that we would like to infer rather than assume. It is a further difficulty to analytically determine whether an estimator is biased or consistent\footnote{An estimator is consistent if-and-only-if its estimate equals the target parameter in the population as the sample size tends to infinity.} without having its sampling distribution. Future research should examine approaches for considering sums of products of random variables in order to obtain distributions that do not assume independence.

Another limitation of some of the statistics defined in this work is the requirement that higher moments exist. Fortunately many commonly-used distributions have finite moments of all positive order. In some cases it may be possible to substitute expectations with the principal Cauchy values of the expectations\footnote{For example, the principal Cauchy value of the expectation of a zero-centered univariate Cauchy random variable is zero even though the first moment is not defined.}, or substitue expectations with medians which are always defined for a random variable.

The work in this thesis focuses on considering hypotheses about particular combinations of variables. This expressiveness leads to an exponentially large class of statistical hypotheses on any finite collection of random variables. If the particular combinations of variables can be used to test specific hypotheses, then immediately we have an exponential complexity (or worse) problem. When it comes to hypothesis testing there is the problem of inflated family-wise error rate that comes from performing many Fisher-Neyman hypothesis tests.\footnote{Fisher-Neyman hypothesis testing is what is often taught in statistics courses as \textit{hypothesis testing}.} While this can be countered with multiple correction methods such as Benjamini-Hochberg corrections, such corrections also result in lower statistical power. Future research should investigate how to usefully search the space of possible hypotheses.

The Agnesian operators bring the Trinity of Covariation into the realm of calculus by quantifing coordinated changes that are either instantaneous, implicit, or accumulated over an interval over some parameter. Future research is warranted to explore how the Agnesian operator can be applied in areas of mathematics and science that are already using calculus, or models amenable to calculus. Some of these subjects potentially include multivariable calculus, differential geometry, linear algebra, multilinear algebra, and differential equations. The Agnesian operators do not make use of mathematical statistics, however they may find application in the subject of stochastic differential equations.

Grade entropies and pseudograde entropies allow us to quantify the totality of partial orders. In the case of grade entropies for product orders, we learn about the comonotonicity of a collection of variables as they change value from observation-to-observation. Partial orders are ubiquitous in mathematics and the natural sciences. Some examples of partial orders include organizational trees of corporations, evolutionary trees, causal graphs \cite{Pearl2009}, assembly histories \cite{Marshall2021}, social hierachies, and the dependency of subroutines in a concurrent computer program.

A product of this thesis is the ConAction Python package. It provides an easy-to-install and easy-to-use way of applying the mathematical notions developed in this thesis. This initial release has been tested for correctness and performance, documented online and in code, and there exists opportunities for improvements \textit{via} user feedback on GitHub.

We were able to evaluate the correlational sufficiency of a classic isolation-by-distance model on mountain pine beetle population data in western North America, and discovered that there exists a dependence between genetic disimilarity and geographic distance left to be explained in the presence of climate-related covariates. We gave suggestions in the previous chapter on how to further explore this, including 

1. trying different clustering algorithms, 
2. using metrics that satisfy the triangle inequality, and
3. using non-linear regression models that have vanishing isolation-by-distance effects for both large and small distances. 

We also suspect that using geographical distance as arc lengths on a sphere may be less informative than distances over land that consider topography. Rather, the biological paths (i.e. the paths that an organism actually takes or tends to take) should be more useful in estimating isolation-by-distance effects but are also multivariate and more difficult to estimate.

While we were able to apply the multilinear Pearson correlation coefficient to a real research problem, there is a large number of opportunities to explore applications of the ideas developed in this thesis. It can be used to detect multilinear dependence in complex systems, but it can also be used to check the correlational sufficiency of models throughout the sciences.

In summary, this thesis provides fundamental motivations, mathematical tools, software tools, and a demonstration of applying these tools. In order to tackle complexity in the formal and empirical sciences, we must have a diverse armamentarium. This thesis is a contribution to that armamentarium.
